name: 'Validate Commit Message'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate commit message
        run: |
          PR_TITLE=$(jq -r .pull_request.title < $GITHUB_EVENT_PATH)
          if ! [[ "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert|release)(\(\w+\))?:\ .{1,50}(\n\n.*)?(\n\n(BREAKING\ CHANGE:\ .+|.+#\d+))?$ ]]; then
            echo "Invalid commit message format. Please follow the conventional commit format."
            echo "Expected format: <type>(<scope>): <description>, with valid types: (feat, fix, docs, style, refactor, test, chore, build, ci, perf, revert, release)."
            exit 1
          fi
